/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WaitlistRouteImport } from './routes/waitlist'
import { Route as SurveysRouteImport } from './routes/surveys'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as SurveysBoardSelectionRouteImport } from './routes/surveys/board-selection'
import { Route as DemoTanstackQueryRouteImport } from './routes/demo.tanstack-query'
import { Route as DashboardGymRouteImport } from './routes/dashboard/gym'
import { Route as DashboardAdminRouteImport } from './routes/dashboard/admin'
import { Route as DashboardAccountRouteImport } from './routes/dashboard/account'
import { Route as DashboardGymGymSettingsRouteImport } from './routes/dashboard/gym/gym-settings'
import { Route as DashboardAdminWaitlistRouteImport } from './routes/dashboard/admin/waitlist'
import { Route as DashboardAdminSurveysRouteImport } from './routes/dashboard/admin/surveys'

const WaitlistRoute = WaitlistRouteImport.update({
  id: '/waitlist',
  path: '/waitlist',
  getParentRoute: () => rootRouteImport,
} as any)
const SurveysRoute = SurveysRouteImport.update({
  id: '/surveys',
  path: '/surveys',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const SurveysBoardSelectionRoute = SurveysBoardSelectionRouteImport.update({
  id: '/board-selection',
  path: '/board-selection',
  getParentRoute: () => SurveysRoute,
} as any)
const DemoTanstackQueryRoute = DemoTanstackQueryRouteImport.update({
  id: '/demo/tanstack-query',
  path: '/demo/tanstack-query',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardGymRoute = DashboardGymRouteImport.update({
  id: '/gym',
  path: '/gym',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAdminRoute = DashboardAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAccountRoute = DashboardAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardGymGymSettingsRoute = DashboardGymGymSettingsRouteImport.update({
  id: '/gym-settings',
  path: '/gym-settings',
  getParentRoute: () => DashboardGymRoute,
} as any)
const DashboardAdminWaitlistRoute = DashboardAdminWaitlistRouteImport.update({
  id: '/waitlist',
  path: '/waitlist',
  getParentRoute: () => DashboardAdminRoute,
} as any)
const DashboardAdminSurveysRoute = DashboardAdminSurveysRouteImport.update({
  id: '/surveys',
  path: '/surveys',
  getParentRoute: () => DashboardAdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/surveys': typeof SurveysRouteWithChildren
  '/waitlist': typeof WaitlistRoute
  '/dashboard/account': typeof DashboardAccountRoute
  '/dashboard/admin': typeof DashboardAdminRouteWithChildren
  '/dashboard/gym': typeof DashboardGymRouteWithChildren
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/surveys/board-selection': typeof SurveysBoardSelectionRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/admin/surveys': typeof DashboardAdminSurveysRoute
  '/dashboard/admin/waitlist': typeof DashboardAdminWaitlistRoute
  '/dashboard/gym/gym-settings': typeof DashboardGymGymSettingsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/surveys': typeof SurveysRouteWithChildren
  '/waitlist': typeof WaitlistRoute
  '/dashboard/account': typeof DashboardAccountRoute
  '/dashboard/admin': typeof DashboardAdminRouteWithChildren
  '/dashboard/gym': typeof DashboardGymRouteWithChildren
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/surveys/board-selection': typeof SurveysBoardSelectionRoute
  '/dashboard': typeof DashboardIndexRoute
  '/dashboard/admin/surveys': typeof DashboardAdminSurveysRoute
  '/dashboard/admin/waitlist': typeof DashboardAdminWaitlistRoute
  '/dashboard/gym/gym-settings': typeof DashboardGymGymSettingsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/surveys': typeof SurveysRouteWithChildren
  '/waitlist': typeof WaitlistRoute
  '/dashboard/account': typeof DashboardAccountRoute
  '/dashboard/admin': typeof DashboardAdminRouteWithChildren
  '/dashboard/gym': typeof DashboardGymRouteWithChildren
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/surveys/board-selection': typeof SurveysBoardSelectionRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/admin/surveys': typeof DashboardAdminSurveysRoute
  '/dashboard/admin/waitlist': typeof DashboardAdminWaitlistRoute
  '/dashboard/gym/gym-settings': typeof DashboardGymGymSettingsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/surveys'
    | '/waitlist'
    | '/dashboard/account'
    | '/dashboard/admin'
    | '/dashboard/gym'
    | '/demo/tanstack-query'
    | '/surveys/board-selection'
    | '/dashboard/'
    | '/dashboard/admin/surveys'
    | '/dashboard/admin/waitlist'
    | '/dashboard/gym/gym-settings'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/surveys'
    | '/waitlist'
    | '/dashboard/account'
    | '/dashboard/admin'
    | '/dashboard/gym'
    | '/demo/tanstack-query'
    | '/surveys/board-selection'
    | '/dashboard'
    | '/dashboard/admin/surveys'
    | '/dashboard/admin/waitlist'
    | '/dashboard/gym/gym-settings'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/surveys'
    | '/waitlist'
    | '/dashboard/account'
    | '/dashboard/admin'
    | '/dashboard/gym'
    | '/demo/tanstack-query'
    | '/surveys/board-selection'
    | '/dashboard/'
    | '/dashboard/admin/surveys'
    | '/dashboard/admin/waitlist'
    | '/dashboard/gym/gym-settings'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  SurveysRoute: typeof SurveysRouteWithChildren
  WaitlistRoute: typeof WaitlistRoute
  DemoTanstackQueryRoute: typeof DemoTanstackQueryRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/waitlist': {
      id: '/waitlist'
      path: '/waitlist'
      fullPath: '/waitlist'
      preLoaderRoute: typeof WaitlistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/surveys': {
      id: '/surveys'
      path: '/surveys'
      fullPath: '/surveys'
      preLoaderRoute: typeof SurveysRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/surveys/board-selection': {
      id: '/surveys/board-selection'
      path: '/board-selection'
      fullPath: '/surveys/board-selection'
      preLoaderRoute: typeof SurveysBoardSelectionRouteImport
      parentRoute: typeof SurveysRoute
    }
    '/demo/tanstack-query': {
      id: '/demo/tanstack-query'
      path: '/demo/tanstack-query'
      fullPath: '/demo/tanstack-query'
      preLoaderRoute: typeof DemoTanstackQueryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/gym': {
      id: '/dashboard/gym'
      path: '/gym'
      fullPath: '/dashboard/gym'
      preLoaderRoute: typeof DashboardGymRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/admin': {
      id: '/dashboard/admin'
      path: '/admin'
      fullPath: '/dashboard/admin'
      preLoaderRoute: typeof DashboardAdminRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/account': {
      id: '/dashboard/account'
      path: '/account'
      fullPath: '/dashboard/account'
      preLoaderRoute: typeof DashboardAccountRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/gym/gym-settings': {
      id: '/dashboard/gym/gym-settings'
      path: '/gym-settings'
      fullPath: '/dashboard/gym/gym-settings'
      preLoaderRoute: typeof DashboardGymGymSettingsRouteImport
      parentRoute: typeof DashboardGymRoute
    }
    '/dashboard/admin/waitlist': {
      id: '/dashboard/admin/waitlist'
      path: '/waitlist'
      fullPath: '/dashboard/admin/waitlist'
      preLoaderRoute: typeof DashboardAdminWaitlistRouteImport
      parentRoute: typeof DashboardAdminRoute
    }
    '/dashboard/admin/surveys': {
      id: '/dashboard/admin/surveys'
      path: '/surveys'
      fullPath: '/dashboard/admin/surveys'
      preLoaderRoute: typeof DashboardAdminSurveysRouteImport
      parentRoute: typeof DashboardAdminRoute
    }
  }
}

interface DashboardAdminRouteChildren {
  DashboardAdminSurveysRoute: typeof DashboardAdminSurveysRoute
  DashboardAdminWaitlistRoute: typeof DashboardAdminWaitlistRoute
}

const DashboardAdminRouteChildren: DashboardAdminRouteChildren = {
  DashboardAdminSurveysRoute: DashboardAdminSurveysRoute,
  DashboardAdminWaitlistRoute: DashboardAdminWaitlistRoute,
}

const DashboardAdminRouteWithChildren = DashboardAdminRoute._addFileChildren(
  DashboardAdminRouteChildren,
)

interface DashboardGymRouteChildren {
  DashboardGymGymSettingsRoute: typeof DashboardGymGymSettingsRoute
}

const DashboardGymRouteChildren: DashboardGymRouteChildren = {
  DashboardGymGymSettingsRoute: DashboardGymGymSettingsRoute,
}

const DashboardGymRouteWithChildren = DashboardGymRoute._addFileChildren(
  DashboardGymRouteChildren,
)

interface DashboardRouteChildren {
  DashboardAccountRoute: typeof DashboardAccountRoute
  DashboardAdminRoute: typeof DashboardAdminRouteWithChildren
  DashboardGymRoute: typeof DashboardGymRouteWithChildren
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardAccountRoute: DashboardAccountRoute,
  DashboardAdminRoute: DashboardAdminRouteWithChildren,
  DashboardGymRoute: DashboardGymRouteWithChildren,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

interface SurveysRouteChildren {
  SurveysBoardSelectionRoute: typeof SurveysBoardSelectionRoute
}

const SurveysRouteChildren: SurveysRouteChildren = {
  SurveysBoardSelectionRoute: SurveysBoardSelectionRoute,
}

const SurveysRouteWithChildren =
  SurveysRoute._addFileChildren(SurveysRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRouteWithChildren,
  SurveysRoute: SurveysRouteWithChildren,
  WaitlistRoute: WaitlistRoute,
  DemoTanstackQueryRoute: DemoTanstackQueryRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
