

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;


COMMENT ON SCHEMA "public" IS 'standard public schema';



CREATE EXTENSION IF NOT EXISTS "pg_graphql" WITH SCHEMA "graphql";






CREATE EXTENSION IF NOT EXISTS "pg_stat_statements" WITH SCHEMA "extensions";






CREATE EXTENSION IF NOT EXISTS "pgcrypto" WITH SCHEMA "extensions";






CREATE EXTENSION IF NOT EXISTS "supabase_vault" WITH SCHEMA "vault";






CREATE EXTENSION IF NOT EXISTS "uuid-ossp" WITH SCHEMA "extensions";






CREATE TYPE "public"."USER_ROLE_TYPE" AS ENUM (
    'ADMIN',
    'MEMBER',
    'COACH'
);


ALTER TYPE "public"."USER_ROLE_TYPE" OWNER TO "postgres";

SET default_tablespace = '';

SET default_table_access_method = "heap";


CREATE TABLE IF NOT EXISTS "public"."AccessLogs" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "climber_id" "uuid",
    "granted" boolean,
    "reason" "text"
);


ALTER TABLE "public"."AccessLogs" OWNER TO "postgres";


COMMENT ON TABLE "public"."AccessLogs" IS 'log every time someone enters the building';



ALTER TABLE "public"."AccessLogs" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."AccessLogs_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."BoardVotes" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "email" "text",
    "votesMap" json
);


ALTER TABLE "public"."BoardVotes" OWNER TO "postgres";


ALTER TABLE "public"."BoardVotes" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."BoardVotes_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."Climber" (
    "id" "uuid" NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "first_name" "text",
    "last_name" "text",
    "email" "text",
    "user_type" "public"."USER_ROLE_TYPE" DEFAULT 'MEMBER'::"public"."USER_ROLE_TYPE" NOT NULL,
    "stripe_customer_id" "text",
    "managed_gym_id" "uuid"
);


ALTER TABLE "public"."Climber" OWNER TO "postgres";


COMMENT ON TABLE "public"."Climber" IS 'customer';



CREATE TABLE IF NOT EXISTS "public"."Gyms" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "name" "text",
    "address" "text",
    "is_enrollment_open" boolean
);


ALTER TABLE "public"."Gyms" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."UserFeedback" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "feedback" "text",
    "user_id" bigint
);


ALTER TABLE "public"."UserFeedback" OWNER TO "postgres";


ALTER TABLE "public"."UserFeedback" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."UserFeedback_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."WaitlistUsers" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "full_name" "text",
    "email" "text"
);


ALTER TABLE "public"."WaitlistUsers" OWNER TO "postgres";


COMMENT ON TABLE "public"."WaitlistUsers" IS 'early sign ups to notify when we start';



ALTER TABLE "public"."WaitlistUsers" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."WaitlistUsers_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



ALTER TABLE ONLY "public"."AccessLogs"
    ADD CONSTRAINT "AccessLogs_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."BoardVotes"
    ADD CONSTRAINT "BoardVotes_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."Climber"
    ADD CONSTRAINT "Climber_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."Gyms"
    ADD CONSTRAINT "Gyms_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."UserFeedback"
    ADD CONSTRAINT "UserFeedback_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."WaitlistUsers"
    ADD CONSTRAINT "WaitlistUsers_email_key" UNIQUE ("email");



ALTER TABLE ONLY "public"."WaitlistUsers"
    ADD CONSTRAINT "WaitlistUsers_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."AccessLogs"
    ADD CONSTRAINT "AccessLogs_climber_id_fkey" FOREIGN KEY ("climber_id") REFERENCES "public"."Climber"("id");



ALTER TABLE ONLY "public"."Climber"
    ADD CONSTRAINT "Climber_id_fkey" FOREIGN KEY ("id") REFERENCES "auth"."users"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."Climber"
    ADD CONSTRAINT "Climber_managed_gym_id_fkey" FOREIGN KEY ("managed_gym_id") REFERENCES "public"."Gyms"("id");



ALTER TABLE ONLY "public"."UserFeedback"
    ADD CONSTRAINT "UserFeedback_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "public"."WaitlistUsers"("id");



ALTER TABLE "public"."Climber" ENABLE ROW LEVEL SECURITY;


CREATE POLICY "Enable insert for authenticated users only" ON "public"."Climber" FOR INSERT TO "authenticated" WITH CHECK (true);



CREATE POLICY "Enable insert for users based on user_id" ON "public"."Climber" FOR INSERT WITH CHECK ((( SELECT "auth"."uid"() AS "uid") = "id"));



CREATE POLICY "Enable read access for all users" ON "public"."Gyms" FOR SELECT USING (true);



CREATE POLICY "Enable users to view their own data only" ON "public"."Climber" FOR SELECT TO "authenticated" USING ((( SELECT "auth"."uid"() AS "uid") = "id"));



ALTER TABLE "public"."Gyms" ENABLE ROW LEVEL SECURITY;


CREATE POLICY "Policy with table joins" ON "public"."Gyms" FOR UPDATE USING (("id" IN ( SELECT "Climber"."managed_gym_id"
   FROM "public"."Climber"
  WHERE ("auth"."uid"() = "Climber"."id"))));





ALTER PUBLICATION "supabase_realtime" OWNER TO "postgres";


GRANT USAGE ON SCHEMA "public" TO "postgres";
GRANT USAGE ON SCHEMA "public" TO "anon";
GRANT USAGE ON SCHEMA "public" TO "authenticated";
GRANT USAGE ON SCHEMA "public" TO "service_role";








































































































































































GRANT ALL ON TABLE "public"."AccessLogs" TO "anon";
GRANT ALL ON TABLE "public"."AccessLogs" TO "authenticated";
GRANT ALL ON TABLE "public"."AccessLogs" TO "service_role";



GRANT ALL ON SEQUENCE "public"."AccessLogs_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."AccessLogs_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."AccessLogs_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."BoardVotes" TO "anon";
GRANT ALL ON TABLE "public"."BoardVotes" TO "authenticated";
GRANT ALL ON TABLE "public"."BoardVotes" TO "service_role";



GRANT ALL ON SEQUENCE "public"."BoardVotes_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."BoardVotes_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."BoardVotes_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."Climber" TO "anon";
GRANT ALL ON TABLE "public"."Climber" TO "authenticated";
GRANT ALL ON TABLE "public"."Climber" TO "service_role";



GRANT ALL ON TABLE "public"."Gyms" TO "anon";
GRANT ALL ON TABLE "public"."Gyms" TO "authenticated";
GRANT ALL ON TABLE "public"."Gyms" TO "service_role";



GRANT ALL ON TABLE "public"."UserFeedback" TO "anon";
GRANT ALL ON TABLE "public"."UserFeedback" TO "authenticated";
GRANT ALL ON TABLE "public"."UserFeedback" TO "service_role";



GRANT ALL ON SEQUENCE "public"."UserFeedback_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."UserFeedback_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."UserFeedback_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."WaitlistUsers" TO "anon";
GRANT ALL ON TABLE "public"."WaitlistUsers" TO "authenticated";
GRANT ALL ON TABLE "public"."WaitlistUsers" TO "service_role";



GRANT ALL ON SEQUENCE "public"."WaitlistUsers_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."WaitlistUsers_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."WaitlistUsers_id_seq" TO "service_role";









ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "service_role";






ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "service_role";






ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "service_role";






























drop extension if exists "pg_net";


